# Azure OpenAI Secrets
AZURE_OPENAI_API_KEY = "0c4813507d9e4dec8b3c0e74bc61a901"
AZURE_OPENAI_API_VERSION = "2023-08-01-preview"
AZURE_OPENAI_ENDPOINT = "https://luminous-ai.openai.azure.com/"
AZURE_OPENAI_DEPLOYMENT_NAME = "Luminous_AI"
AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME = "Language_Model"

# Astra DB Secrets
ASTRA_API_ENDPOINT = "https://fda864bf-3f0a-4d6c-9638-59f0f3f501dc-us-east-2.apps.astra.datastax.com"
ASTRA_TOKEN = "AstraCS:fOvEpwZOSuhKUXQuKpXILOak:4ef45d4edcb6d9c0f125400e8d8d2e2e07148bc9f85b7e12e3899d6c3a54c04b"

LANGCHAIN_ENDPOINT = "https://api.smith.langchain.com"
LANGCHAIN_API_KEY = "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"
LANGCHAIN_PROJECT="pr-tragic-mangrove-26"
LANGCHAIN_TRACING_V2 = "true"

OPEN_API_KEY = "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"
OPENAI_API_KEY = "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"
